trigger:
- sample

variables:
  - group: ios-pipeline

pool:
  vmImage: 'macos-13'

steps:

- script: |
    rm Gemfile.lock
    bundle install
    bundle exec arkana
  displayName: 'Bundle install and execute arkana'

